[package]
name = "rs-cpu-svo"
version = "0.1.0"
authors = ["Max Breitenfeldt <git@mxbr.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath = { version = "0.17.0", features = ["serde", "swizzle"] }
serde = "1.0.105"
csv = "1.1"
rayon="1.1"
minifb = "0.16"
